"use strict";
let places = [`Portgrand`, `Meritime mueseum`, `Hill park`,`clifton`, `muree`];
console.log(`original` + places);
console.log(`copy` + [...places].sort());
console.log(places);
console.log([...places].sort().reverse());
console.log(places);
console.log(places.reverse());
console.log(places.reverse());
console.log(places.sort());
console.log(places.sort().reverse());
